sonar.projectKey=jhl-labs_k8sage
sonar.projectName=jhl-labs/k8sage
sonar.sources=.
sonar.exclusions=**/.git/**,**/node_modules/**,**/reports/**,**/coverage/**,**/dist/**,**/build/**,**/.next/**,**/vendor/**
